### ISSUE TITLE
Test Update

### ISSUE THREAD

**Issue by DeadlySquad13** [RDcool/BMSTU_AHP#1]
Issue testing update

**Comment by feelsbadmans** [comment]
Судя по коммитам владелец репозитория все пары КИСа отходил, причём на пэтушиной зоне. Чисто красножопик. Покажи что тебе в МРе написали, чуханавт дырявый. Я бы тебя в дупло отревьюил. Додик сидит со своими юпитер ноутбуками и мухлыжит там. Очкан. 

**_P.S._** Где 4, 5, 6, 7 лабы ?)
_**P.P.S**_ Похрюкай

![misha](https://user-images.githubusercontent.com/62965405/231961891-6342fb69-7912-41a5-980a-e4293232d3af.gif)

**Comment by Frisky211** [comment]
Михаил, мы понимаем: диплом, зачеты, экзамены, но исследования в рамках КИС сами себя не сделают. Вы вынуждаете своих коллег думать самостоятельно, что антипозитивно влияет на чилибас. Настоятельно рекомендуем Вам поднапрячься, осталось совсем чуть-чуть. Иначе как Вам нас душить? Слава Коммунистическим Интеллектуальным Системам.
![Миша делает кис](https://user-images.githubusercontent.com/70955624/232100491-80ff1563-1d01-47bf-9429-5e85ea321e26.png)

С позитивом,
биба

**Comment by RDcool** [comment]
Добавил [лабы](https://github.com/RDcool/BMSTU_AHP/commit/491285239981e82c94e128b2fe0621f4dab9ee08) для вас, бездари (без негатива). Enjoy )

P. S. В лабе 4 жидкий эксперимент, в лабе 5 очень жидкий эксперимент и формулы могут меняться в зависимости наличия ограничения на очередь
